spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:boarddb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 85903398911-capa3i3n0aodmnrvljmnfpr6epnue5gq.apps.googleusercontent.com
            client-secret: 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